env:
  TERM: xterm-256color

window:
  dynamic_padding: true

font:
  size: 13
  normal:
    family: JetBrains Mono NL

colors:
  cursor:
    cursor: '0xeeeeee'

  # Default colors
  primary:
    background: '0x0d0d0d'
    foreground: '0xeeeeee'

  # Normal colors
  normal:
    black:   '0x1b1d1e'
    red:     '0xf92672'
    green:   '0x82b414'
    yellow:  '0xfd971f'
    blue:    '0x0063af'
    magenta: '0x8c54fe'
    cyan:    '0x465457'
    white:   '0xb5b5b5'

  # Bright colors
  bright:
    black:   '0x505354'
    red:     '0xff5995'
    green:   '0xb6e354'
    yellow:  '0xfeed6c'
    blue:    '0x238cdc'
    magenta: '0x9e6ffe'
    cyan:    '0x899ca1'
    white:   '0xf8f8f2'

