env:
  TERM: xterm-256color

window:
  decorations: none
  padding:
    x: 5
    y: 5

mouse:
  url:
    launcher:
      program: xdg-open

font:
  size: 12.0

  normal:
    family: Source Code Pro
    style: Medium

  bold:
    style: Bold

  italic:
    style: Italic

  bold_italic:
    style: Bold Italic
  
colors:
  cursor:
    cursor: '0xbbbbbb'

  primary:
    background: '0x0b0b0b'
    foreground: '0xbbbbbb'
    bright_foreground: '0xffffff'

  normal:
    black: '0x1b1918'
    red: '0xf22c40'
    green: '0x5ab738'
    yellow: '0xd5911a'
    blue: '0x3971ed'
    magenta: '0xe85b92'
    cyan: '0x00ad9c'
    white: '0xcccccc'

  bright:
    black: '0x4f4f4f'
    red: '0xf85262'
    green: '0x7bd15b'
    yellow: '0xe9ad44'
    blue: '0x5e8af1'
    magenta: '0xf181ac'
    cyan: '0x26b3a4'
    white: '0x848282'

