env:
  TERM: xterm-256color

window:
  dynamic_padding: true

font:
  size: 13
  normal:
    family: monospace

colors:
  cursor:
    cursor: '0xeeeeee'

  # Default colors
  primary:
    background: '0x0d0d0d'
    foreground: '0xeeeeee'

  # Normal colors
  normal:
    black:   '0x1f1f1f'
    red:     '0xf92645'
    green:   '0x82b414'
    yellow:  '0xfdbe25'
    blue:    '0x0c68af'
    magenta: '0x8c54fe'
    cyan:    '0x13a5a2'
    white:   '0x858585'

  # Bright colors
  bright:
    black:   '0x454545'
    red:     '0xfc899a'
    green:   '0xb6ea44'
    yellow:  '0xfedc8a'
    blue:    '0x309df1'
    magenta: '0xd0b9ff'
    cyan:    '0x36e8e4'
    white:   '0xffffff'
