#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        # shellcheck source=/etc/X11/xinit/xinitrc.d/*
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

if [ -f ~/.Xresources ]; then
    xrdb -load -I "$HOME" ~/.Xresources
fi

setxkbmap -option compose:ralt,caps:super
unclutter --timeout 5 --jitter 10 --exclude-root --fork
xset +fp ~/.local/share/fonts/

# Make left side buttons for mouse act as middle click. Thanks steelseries for the weak af wheel.
MOUSE_ID=$(xinput | grep -m 1 "SteelSeries Sensei" | sed 's/^.*id=\([0-9]*\)[ \t].*$/\1/')
xinput --set-button-map "$MOUSE_ID" 1 2 3 4 5 6 7 2 2 10 11 12 13 14 15 16

unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  auth_socket=$(gpgconf --list-dirs agent-ssh-socket)
  export SSH_AUTH_SOCK="$auth_socket"
fi

## {{ Refresh gpg-agent tty in case user switches into an X session
# Wait for gpg-agent to actually start
while ! pidof gpg-agent >/dev/null 2>&1
do
    sleep 0.1
done

gpg_tty=$(tty)
export GPG_TTY="$gpg_tty"
gpg-connect-agent updatestartuptty /bye >/dev/null
## }}

/usr/libexec/polkit-gnome-authentication-agent-1 >/dev/null 2>&1 &

exec awesome
