#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        # shellcheck source=/etc/X11/xinit/xinitrc.d/*
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

if [ -f "$XDG_CONFIG_HOME/X11/Xresources" ]; then
    xrdb -load -I "$XDG_CONFIG_HOME/X11" $XDG_CONFIG_HOME/X11/Xresources
fi

unclutter --timeout 5 --jitter 10 --exclude-root --fork
xset +fp ~/.local/share/fonts/

unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  auth_socket=$(gpgconf --list-dirs agent-ssh-socket)
  export SSH_AUTH_SOCK="$auth_socket"
fi

/usr/libexec/polkit-gnome-authentication-agent-1 >/dev/null 2>&1 &

# Disable GTK3 accessibility
export NO_AT_BRIDGE=1

export QT_QPA_PLATFORMTHEME=gtk3
export XCURSOR_PATH="${XCURSOR_PATH}:${XDG_DATA_HOME}/icons"

exec awesome
