alias rsync "rsync --progress"
alias grep 'grep --color=auto'
alias more 'less'
alias less 'less --RAW-CONTROL-CHARS'
alias df 'df -h'
alias du 'du -c -h'
alias mkdir 'mkdir -p -v'
alias ping 'ping -c 5'
alias ls 'ls --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias ll 'ls -lh --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias la 'ls -lha --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
